name: Build edk2-rk3399

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        rm ~/.gitconfig
        sudo apt install -y build-essential uuid-dev iasl git nasm python3-distutils gcc-aarch64-linux-gnu

    - name: Clone repositories
      run: |
        mkdir workspace-edk2
        cd workspace-edk2
        git config --global protocol.file.allow always
        git clone https://github.com/tianocore/edk2.git -o 5801910013757bd626f67ed77eea6c16a176eebf --recursive --depth=1
        git clone https://github.com/tianocore/edk2-platforms.git -o d8232e8816fafb875a3656dda788b6681bc25149 --recursive --depth=1
        git clone https://github.com/edk2-porting/edk2-rk3399.git

    - name: Build edk2-rk3399
      working-directory: workspace-edk2/edk2-rk3399
      run: |
        bash build.sh --device polaris
