name: Build edk2-rk3399

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential uuid-dev iasl git nasm python3-distutils gcc-aarch64-linux-gnu

    - name: Clone repositories
      run: |
        mkdir workspace-edk2
        cd workspace-edk2
        git config --global protocol.file.allow always
        git clone https://github.com/tianocore/edk2.git -o 3a3713e62cfad00d78bb938b0d9fb1eedaeff314 --recursive --depth=1
        git clone https://github.com/tianocore/edk2-platforms.git -o cfdc7f907d545b14302295b819ea078bc36c6a40 --recursive --depth=1
        git clone https://github.com/edk2-porting/edk2-rk3399.git

    - name: Build edk2-rk3399
      working-directory: workspace-edk2/edk2-rk3399
      run: |
        bash build.sh --device polaris
