name: Build edk2-rk3399

on:
  push:

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt remove git
        sudo apt autoremove
        sudo apt install -y git build-essential uuid-dev iasl git nasm python3-distutils gcc-aarch64-linux-gnu

    - name: Clone repositories
      run: |
        mkdir workspace-edk2
        cd workspace-edk2
        git config --global protocol.file.allow always
        git clone https://github.com/tianocore/edk2.git -b edk2-stable202002 --recursive --depth=1
        git clone https://github.com/tianocore/edk2-platforms.git -o cfdc7f907d545b14302295b819ea078bc36c6a40 --recursive --depth=1
        git clone https://github.com/mouseos/edk2-rk3399/

    - name: Build edk2-rk3399
      working-directory: workspace-edk2/edk2-rk3399
      run: |
        bash build.sh --device polaris
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: zmooth-edk2
        path: |
          edk2-rk3399/workspace/Build/sdm845Pkg/DEBUG_GCC5/FV/SDM845PKG_UEFI.fd
        if-no-files-found: ignore
