name: Build edk2-rk3399

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential uuid-dev iasl git nasm python3-distutils gcc-aarch64-linux-gnu

    - name: Clone repositories
      run: |
        mkdir workspace-edk2
        cd workspace-edk2
        git config --global protocol.file.allow always
        git clone https://github.com/tianocore/edk2.git  --recursive 
        cd edk2
        git checkout 4ac0296
        git checkout --recurse-submodules 38c8be123aced4cc8ad5c7e0da9121a181b94251
        cd ..
        git clone https://github.com/tianocore/edk2-platforms.git --recursive --depth=1
        git clone https://github.com/edk2-porting/edk2-rk3399.git

    - name: Build edk2-rk3399
      working-directory: workspace-edk2/edk2-rk3399
      run: |
        bash build.sh --device polaris
